"""Typed domain models for the platform. See docs/DATA_MODEL.md."""

from trp.domain.changes import (
    Acquisition,
    ChangeError,
    Delisting,
    EntityRename,
    ExchangeMove,
    SecurityEvent,
    TickerChange,
    apply_entity_rename,
    apply_event,
    apply_exchange_move,
    apply_termination,
    apply_ticker_change,
)
from trp.domain.identifier_map import IdentifierRecord, MappingConflict, find_mapping_conflicts
from trp.domain.identifiers import (
    EntityId,
    IdentifierKind,
    SecurityId,
    new_entity_id,
    new_security_id,
)
from trp.domain.master import TERMINAL_STATUSES, SecurityMaster
from trp.domain.pit import PointInTimeSecurityMaster, known_as_of, listings_on, status_on
from trp.domain.resolution import (
    AmbiguousIdentifier,
    IdentifierResolver,
    ResolutionError,
    UnknownIdentifier,
)
from trp.domain.security import (
    DelistingReason,
    EffectiveDated,
    Entity,
    FrozenModel,
    Listing,
    Security,
    SecurityStatus,
    SecurityStatusPeriod,
    SecurityType,
    revalidated_copy,
)

__all__ = [
    "TERMINAL_STATUSES",
    "Acquisition",
    "AmbiguousIdentifier",
    "ChangeError",
    "Delisting",
    "DelistingReason",
    "EffectiveDated",
    "Entity",
    "EntityId",
    "EntityRename",
    "ExchangeMove",
    "FrozenModel",
    "IdentifierKind",
    "IdentifierRecord",
    "IdentifierResolver",
    "Listing",
    "MappingConflict",
    "PointInTimeSecurityMaster",
    "ResolutionError",
    "Security",
    "SecurityEvent",
    "SecurityId",
    "SecurityMaster",
    "SecurityStatus",
    "SecurityStatusPeriod",
    "SecurityType",
    "TickerChange",
    "UnknownIdentifier",
    "apply_entity_rename",
    "apply_event",
    "apply_exchange_move",
    "apply_termination",
    "apply_ticker_change",
    "find_mapping_conflicts",
    "known_as_of",
    "listings_on",
    "new_entity_id",
    "new_security_id",
    "revalidated_copy",
    "status_on",
]
